### ISSUE TITLE
Initial set up of the project codebase

### ISSUE THREAD

**Issue by chenejac** [chenejac/TeslaRIS-backend#1]
**Tasks**
- [x] Maven
- [x] Spring + Spring boot
    - [x] Spring security
    - [x] Spring web
    - [x] Spring data JPA
    - [x] Spring data elastic
    - [x] Tomcat starter
    - [x] ElasticSearch starter
    - [x] Lombok ???
    - [x] Spring Apache Kafka ???
    - [x] Spring REST docs ???
- [x] Modules - see at https://docs.google.com/document/d/1zVKpdft0jXv_wtOoRusta8PxN_aNhyFuqXfsddbmiY4/edit?usp=sharing
- [x] Unit tests for each module
- [x] Integration tests
- [x] Checkstyle - adopt [VIVO](https://wiki.lyrasis.org/display/VIVO/Code+Style+Guide) or [Google Java style](https://google.github.io/styleguide/javaguide.html)
- [x] License  
- [x] Readme with installation instructions

**Comment by ivanmrsulja** [comment]
License was allready included: GPL-3.0
