### ISSUE TITLE
Making model

### ISSUE THREAD

**Issue by chenejac** [chenejac/TeslaRIS-backend#3]
**Tasks**
- [x] Making draft model at [draw.io](https://app.diagrams.net/) based on [CRIS UNS DTOs](https://github.com/chenejac/cris/tree/master/src/rs/ac/uns/ftn/informatika/bibliography/dto) 
- [x] Discuss draft model and extend to support local needs (to be in accordance with [specification](https://docs.google.com/document/d/1zVKpdft0jXv_wtOoRusta8PxN_aNhyFuqXfsddbmiY4/edit?usp=sharing)) and to be in accordance with [CERIF](https://github.com/EuroCRIS/CERIF-Core/)
- [x] Making/generating JPA entities
