### ISSUE TITLE
Set up of the security (authentication and authorization)

### ISSUE THREAD

**Issue by chenejac** [chenejac/TeslaRIS-backend#7]
**Is your feature request related to a problem? Please describe.**
The setup of the classes for authentication and authorization is needed.

**Describe the solution you'd like**
The roles we need available at https://docs.google.com/document/d/1zVKpdft0jXv_wtOoRusta8PxN_aNhyFuqXfsddbmiY4/edit#heading=h.l7k92ll7cs2p 
Authentication based on email and password for beginning. 

**Describe alternatives you've considered**
Authentication via ORCID. 

**Additional context**
The groups and privileges used in [CRIS UNS](https://github.com/chenejac/cris/blob/master/src/rs/ac/uns/ftn/informatika/bibliography/jsf/managedbeans/PrivilegesManagedBean.java)

**Tasks**
- [x] Definition of groups and roles
- [x] Definition of privileges 
- [x] Spring security configuration
- [x] Login endpoint
