### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by chenejac** [chenejac/TeslaRIS-backend#8]
**Tasks**
- [x] CRUD operations over basic data about Users
- [x] Linking user to group
- [x] Registration of user (for researchers)
    - [x]  email with activation link
    - [x]  encryption of password
- [x] Deactivation of user
- [x] #13
